TC := "C:/Users/24151/Documents/GitHub/无痕hook/KernelPatch/arm-gnu-toolchain-15.2.rel1-mingw-w64-x86_64-aarch64-none-elf/bin/aarch64-none-elf-"
KP := "C:/Users/24151/Documents/GitHub/无痕hook/KernelPatch"

default: build push

build:
    #!/usr/bin/env bash
    export TMP="$(pwd)"
    export TEMP="$(pwd)"
    make -C "{{justfile_directory()}}" TARGET_COMPILE={{TC}} KP_DIR={{KP}} CFLAGS="-fno-builtin -pipe" clean all

push:
    MSYS_NO_PATHCONV=1 adb push "{{justfile_directory()}}/kdbg-probe.kpm" "/sdcard/Download/kdbg-probe.kpm"
