TC := "C:/Users/24151/Documents/GitHub/KernelPatch/arm-gnu-toolchain-15.2.rel1-mingw-w64-x86_64-aarch64-none-elf/bin/aarch64-none-elf-"
KP := "C:/Users/24151/Documents/GitHub/xiaojia-hide/KernelPatch"

default: build push

build:
    make -C "{{justfile_directory()}}" TARGET_COMPILE={{TC}} KP_DIR={{KP}} clean all

push:
    MSYS_NO_PATHCONV=1 adb push "{{justfile_directory()}}/xiam-tools.kpm" /sdcard/Download/

NDK := "C:/Users/24151/AppData/Local/Android/Sdk/ndk/29.0.13113456"
CC_ANDROID := NDK + "/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android35-clang"

detect: detect-build detect-push

detect-build:
    {{CC_ANDROID}} -o "{{justfile_directory()}}/detect_demo" "{{justfile_directory()}}/detect_demo.c" -static -O2

detect-push:
    MSYS_NO_PATHCONV=1 adb push "{{justfile_directory()}}/detect_demo" /data/local/tmp/
